// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Header$ReactHooksTemplate = require("./Header.bs.js");
var ReposList$ReactHooksTemplate = require("./ReposList.bs.js");

function string(prim) {
  return prim;
}

function App(Props) {
  return React.createElement("div", {
              className: "container-flex"
            }, React.createElement(Header$ReactHooksTemplate.make, { }), React.createElement("main", {
                  role: "main"
                }, React.createElement("div", {
                      className: "album py-5 bg-light"
                    }, React.createElement("div", {
                          className: "container"
                        }, React.createElement(ReposList$ReactHooksTemplate.make, { })))));
}

var make = App;

exports.string = string;
exports.make = make;
/* react Not a pure module */
