// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function string(prim) {
  return prim;
}

function Header(Props) {
  var match = React.useState((function () {
          return false;
        }));
  var setNavVisibility = match[1];
  var isNavVisible = match[0];
  var collapse = isNavVisible ? "bg-dark" : "collapse bg-dark";
  return React.createElement("header", undefined, React.createElement("div", {
                  className: collapse,
                  id: "navbarHeader"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: "row"
                        }, React.createElement("div", {
                              className: "col-sm-8 col-md-7 py-4"
                            }, React.createElement("h4", {
                                  className: "text-white"
                                }, "About"), React.createElement("p", {
                                  className: "text-muted"
                                }, "Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.")), React.createElement("div", {
                              className: "col-sm-4 offset-md-1 py-4"
                            }, React.createElement("h4", {
                                  className: "text-white"
                                }, "Contact"), React.createElement("ul", {
                                  className: "list-unstyled"
                                }, React.createElement("li", undefined, React.createElement("a", {
                                          className: "text-white",
                                          href: "#"
                                        }, "Follow on Twitter")), React.createElement("li", undefined, React.createElement("a", {
                                          className: "text-white",
                                          href: "#"
                                        }, "Like on Facebook")), React.createElement("li", undefined, React.createElement("a", {
                                          className: "text-white",
                                          href: "#"
                                        }, "Email me"))))))), React.createElement("div", {
                  className: "navbar navbar-dark bg-dark shadow-sm"
                }, React.createElement("div", {
                      className: "container d-flex justify-content-between"
                    }, React.createElement("a", {
                          className: "navbar-brand d-flex align-items-center",
                          href: "#"
                        }, React.createElement("svg", {
                              "aria-hidden": true,
                              className: "mr-2",
                              height: "20",
                              width: "20",
                              fill: "none",
                              focusable: "false",
                              stroke: "currentColor",
                              strokeLinecap: "round",
                              strokeLinejoin: "round",
                              strokeWidth: "2",
                              viewBox: "0 0 24 24",
                              xmlns: "http://www.w3.org/2000/svg"
                            }, React.createElement("path", {
                                  d: "M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"
                                }), React.createElement("circle", {
                                  cx: "12",
                                  cy: "13",
                                  r: "4"
                                })), React.createElement("strong", undefined, "Album")), React.createElement("button", {
                          "aria-label": "Toggle navigation",
                          "aria-expanded": false,
                          "aria-controls": "navbarHeader",
                          className: "navbar-toggler",
                          type: "button",
                          onClick: (function (_e) {
                              return Curry._1(setNavVisibility, (function (_prev) {
                                            return !isNavVisible;
                                          }));
                            })
                        }, React.createElement("span", {
                              className: "navbar-toggler-icon"
                            })))));
}

var make = Header;

exports.string = string;
exports.make = make;
/* react Not a pure module */
