// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var RepoCard$ReactHooksTemplate = require("./RepoCard.bs.js");
var RepoData$ReactHooksTemplate = require("./RepoData.bs.js");

function string(prim) {
  return prim;
}

function ReposList(Props) {
  var match = React.useState((function () {
          return undefined;
        }));
  var setRepoData = match[1];
  var repoData = match[0];
  React.useEffect((function () {
          RepoData$ReactHooksTemplate.fetchRepos(/* () */0).then((function (repoData) {
                    Curry._1(setRepoData, (function (_prev) {
                            return repoData;
                          }));
                    return Promise.resolve(/* () */0);
                  })).catch((function (err) {
                  console.log("An error occurred: " + String(err));
                  return Promise.resolve(/* () */0);
                }));
          return undefined;
        }), ([]));
  var repoItems = repoData !== undefined ? $$Array.map((function (repo) {
            return React.createElement(RepoCard$ReactHooksTemplate.make, {
                        repo: repo,
                        key: repo[/* html_url */4]
                      });
          }), repoData) : "Loading...";
  console.log(repoData);
  return React.createElement("div", {
              className: "row"
            }, repoItems);
}

var make = ReposList;

exports.string = string;
exports.make = make;
/* react Not a pure module */
