// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function parseGithubOwner(json) {
  return Json_decode.field("login", Json_decode.string, json);
}

function parseRepo(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* description */Json_decode.field("description", (function (param) {
                  return Json_decode.optional(Json_decode.string, param);
                }), json),
          /* stargazers_count */Json_decode.field("stargazers_count", Json_decode.$$int, json),
          /* html_url */Json_decode.field("html_url", Json_decode.string, json),
          /* user */Json_decode.field("owner", parseGithubOwner, json)
        ];
}

function parseGithubResponse(json) {
  return Json_decode.field("items", (function (param) {
                return Json_decode.array(parseRepo, param);
              }), json);
}

var reposUrl = "https://api.github.com/search/repositories?q=user%3Aandreagulp&type=Repositories";

function fetchRepos(param) {
  return fetch(reposUrl).then((function (prim) {
                  return prim.text();
                })).then((function (jsonText) {
                return Promise.resolve(parseGithubResponse(JSON.parse(jsonText)));
              }));
}

exports.parseGithubOwner = parseGithubOwner;
exports.parseRepo = parseRepo;
exports.parseGithubResponse = parseGithubResponse;
exports.reposUrl = reposUrl;
exports.fetchRepos = fetchRepos;
/* No side effect */
