// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function string(prim) {
  return prim;
}

function RepoCard(Props) {
  var repo = Props.repo;
  return React.createElement("div", {
              className: "col-md-4"
            }, React.createElement("div", {
                  className: "card mb-4 shadow-sm"
                }, React.createElement("div", {
                      className: "card-body"
                    }, React.createElement("h5", {
                          className: "card-title"
                        }, repo[/* name */1]), React.createElement("p", {
                          className: "card-text"
                        }, repo[/* description */2]), React.createElement("div", {
                          className: "d-flex justify-content-between align-items-center"
                        }, React.createElement("div", {
                              className: "btn-group"
                            }, React.createElement("button", {
                                  className: "btn btn-sm btn-outline-secondary",
                                  type: "button"
                                }, "Open"), React.createElement("a", {
                                  href: repo[/* html_url */4],
                                  target: "_blank"
                                }, React.createElement("button", {
                                      className: "btn btn-sm btn-outline-secondary",
                                      type: "button"
                                    }, "View"))), React.createElement("small", {
                              className: "text-muted"
                            }, String(repo[/* stargazers_count */3]))))));
}

var make = RepoCard;

exports.string = string;
exports.make = make;
/* react Not a pure module */
